name = "TreeWaveGR"
uuid = "24b64e38-6007-432e-a01c-abae1aa0c36c"
version = "0.1.0"
authors = ["Erik Schnetter <schnetter@gmail.com>"]

[deps]
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
IMEXRungeKutta = "6f46d5f7-e15e-41aa-a098-eed9d1a63ad8"
KernelAbstractions = "63c18a36-062a-441e-b654-da1e3ab1ce7c"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
SpacetimeMetrics = "77e61b41-605e-43a6-b70f-04b7dcd1f572"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
TreeAMR = "91bc416d-811c-44c1-9bc4-b9c8bbdbbd08"
TreeIOHDF5 = "49af10b2-b28a-4989-bafa-527ac30d3246"

[sources]
IMEXRungeKutta = {rev = "main", url = "https://github.com/eschnett/IMEXRungeKutta.jl"}
SpacetimeMetrics = {rev = "main", url = "https://github.com/eschnett/SpacetimeMetrics.jl"}
TreeIOHDF5 = {rev = "main", url = "https://github.com/eschnett/TreeIOHDF5.jl"}

[compat]
ForwardDiff = "1.3.3"
IMEXRungeKutta = "1.3"
KernelAbstractions = "0.9.42, 1"
LinearAlgebra = "1.11"
SpacetimeMetrics = "1.6"
StaticArrays = "1"
TreeAMR = "0.2"
TreeIOHDF5 = "0.1.0"
julia = "1.11"
